spring:
  application:
    name: PatientService

server:
  port: ${portno:9191}
  
eureka: 
  client:  
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:9090/eureka/}
  instance:
    prefer-ip-address: true