server:
  port: 9090
  servlet:
    context-path: /SbiApp
    

spring:
  mvc:
    view:
      prefix: /views/ 
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: y.satishkumar34@gmail.com
    password: Satish@123
    properties:
      mail:
       smtp:
        auth: true
        starttls:
         enable: true
   
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL55Dialect
    
      


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  endpoint:
    env:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    threaddump:
      enabled: true
    heapdump:
      enabled: true
    configprops:
      enabled: true
      

